# Generated by Django 3.2.7 on 2021-11-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=40),
        ),
    ]
