# Generated by Django 3.2.7 on 2021-11-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checkout', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='town_or_city',
            field=models.CharField(max_length=50),
        ),
    ]
