# Generated by Django 3.2.7 on 2021-10-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checkout', '0006_rename_item_total_orderitem_lineitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6, null=True),
        ),
    ]
