# Generated by Django 3.2.7 on 2021-10-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_checkout', '0007_alter_orderitem_lineitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
