# Generated by Django 3.2.7 on 2021-10-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='detail_01',
            field=models.CharField(default='some detail', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_02',
            field=models.CharField(default='some detail', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_03',
            field=models.CharField(default='some detail', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default='some price', max_digits=6),
        ),
    ]
