# Generated by Django 3.2.7 on 2021-10-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_01',
            field=models.CharField(default='some detail', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_02',
            field=models.CharField(default='some detail', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_03',
            field=models.CharField(default='some detail', max_length=1000),
        ),
    ]
