# Generated by Django 3.2.7 on 2021-10-27 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211027_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
