# Generated by Django 3.2.7 on 2021-10-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_01',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_02',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_03',
            field=models.CharField(default='', max_length=100),
        ),
    ]
