# Generated by Django 3.2.7 on 2021-10-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211027_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_01',
            field=models.CharField(default='some detail', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_02',
            field=models.CharField(default='some detail', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail_03',
            field=models.CharField(default='some detail', max_length=100),
        ),
    ]
